name: Test

on:
  push:
    branches:
    - 3.x
    - 3.x-eventblocklists
  pull_request:
    branches:
    - 3.x

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:10
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: misp3_test
          MYSQL_USER: misp
          MYSQL_PASSWORD: misp
        volumes:
          - ./docker/db/misp-2.4.169.sql:/docker-entrypoint-initdb.d/init.sql
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # - name: Start test containers
    #   run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml --env-file="./docker/.env.test" up -d --build

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: php-mysql, php-xml, php-mbstring
        tools: composer:v2

    - name: Install mysql client
      run: sudo apt-get install -y mysql-client

    - name: Populate database
      run: mysql -h db -u misp -pmisp misp3_test < docker/db/misp-2.4.169.sql

    - name: Install composer packages
      run: composer install --no-interaction --no-progress --no-suggest --ignore-platform-reqs

    - name: Copy config file
      run: cp -Rf docker/misp/config/app_local.php config/app_local.php

    - name: Run tests
      run: vendor/bin/phpunit
    
    # - name: Run tests
    #   run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml --env-file="./docker/.env.test" exec --no-TTY misp vendor/bin/phpunit

    # - name: Stop containers
    #   run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml --env-file="./docker/.env.test" down